import type { Metadata } from "next";
import "./globals.css";
import HeaderTop from "@/components/HeaderTop";
import HeaderMain from "@/components/HeaderMain";
import NavBar from "@/components/NavBar";

import "slick-carousel/slick/slick.css"
import "slick-carousel/slick/slick-theme.css"
import MobileNavBar from "@/components/MobileNavBar";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "milestone-3 e-commerce site",
  description: "Generated by ghulam shabbir",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      >
        <header>
          <HeaderTop />
          <HeaderMain />
          <NavBar />
          <MobileNavBar/>
        </header>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
